name: torch2
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h8011034_4
  - arxiv=2.2.0=pyhd8ed1ab_0
  - aws-c-auth=0.9.0=h5eee18b_1
  - aws-c-cal=0.9.2=hdb10cc7_0
  - aws-c-common=0.12.3=h5eee18b_0
  - aws-c-compression=0.3.1=h5eee18b_1
  - aws-c-event-stream=0.5.5=h5eee18b_0
  - aws-c-http=0.10.2=h5eee18b_0
  - aws-c-io=0.20.1=hbcb7957_0
  - aws-c-mqtt=0.13.2=h5eee18b_0
  - aws-c-s3=0.8.3=hdb10cc7_0
  - aws-c-sdkutils=0.2.4=h5eee18b_0
  - aws-checksums=0.2.7=h5eee18b_0
  - aws-crt-cpp=0.32.10=h6a678d5_0
  - aws-sdk-cpp=1.11.528=h9e09249_1
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.15=h06a4308_0
  - cairo=1.16.0=h44eff21_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.4=hbda6634_3
  - cupy-core=13.0.0=py310had4011e_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython-blis=0.7.9=py310ha9d4c09_0
  - dal=2023.1.1=hdb19cb5_48680
  - dav1d=1.2.1=h5eee18b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - feedparser=6.0.11=pyhd8ed1ab_1
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=h39681ba_1
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icecream=2.1.3=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_0
  - jupyter_server=2.16.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.27.3=py310h06a4308_0
  - jupyterlab_widgets=3.0.15=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.14.1=hc1efc7f_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.10.4=hfdd30dd_2
  - libxslt=1.1.37=h5eee18b_1
  - lightning=2.5.3=pyhd8ed1ab_0
  - littleutils=0.2.2=py_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.0=py310hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=mpich
  - mpich=4.1.1=hbae89fd_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbconvert-pandoc=7.16.6=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.4=py310hb5e798b_0
  - ocl-icd=2.3.2=h5eee18b_1
  - ogb=1.3.6=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - orc=2.1.1=hd396ef6_0
  - outdated=0.2.2=pyhd8ed1ab_0
  - p-tqdm=1.4.0=pyhd8ed1ab_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.5.2=py310_torch_2.1.0_cu121
  - python=3.10.13=h955ad1f_0
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.5.3=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - qtconsole-base=5.5.1=pyha770c72_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - s2n=1.5.14=hdbd6064_0
  - sgmllib3k=1.0.0=pyhd3eb1b0_0
  - smart_open=5.2.1=py310h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - tk=8.6.15=h54e0aa7_0
  - torchtriton=2.1.0=py310
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - utf8proc=2.6.1=h5eee18b_1
  - wget=1.25.0=h251f7ec_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.9
    - aiosignal==1.4.0
    - altair==5.5.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.7.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - async-timeout==5.0.1
    - attrs==24.3.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - bertopic==0.16.4
    - bleach==6.2.0
    - blis==0.7.9
    - bottleneck==1.4.2
    - brotli==1.0.9
    - brotlicffi==1.0.9.2
    - catalogue==2.0.10
    - certifi==2025.8.3
    - cffi==1.17.1
    - chardet==4.0.0
    - click==8.2.1
    - cloudpathlib==0.16.0
    - colorama==0.4.6
    - comm==0.2.1
    - confection==0.1.5
    - contourpy==1.3.1
    - cupy==13.0.0
    - curated-tokenizers==0.0.9
    - curated-transformers==0.1.1
    - cymem==2.0.6
    - daal4py==2023.1.1
    - datasets==2.16.1
    - debugpy==1.8.11
    - dgl==2.1.0
    - dill==0.3.7
    - embedded-topic-model==1.2.1
    - en-core-web-sm==3.7.1
    - en-core-web-trf==3.7.3
    - exceptiongroup==1.2.0
    - faiss-gpu==1.7.2
    - fastjsonschema==2.20.0
    - fastopic==0.0.5
    - fastrlock==0.8.3
    - filelock==3.17.0
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2025.7.0
    - gensim==4.3.3
    - gmpy2==2.2.1
    - h11==0.16.0
    - hdbscan==0.8.40
    - hf-xet==1.1.3
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.32.4
    - hydra-core==1.3.2
    - idna==3.7
    - ipython==8.30.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.1
    - json5==0.9.25
    - jsonschema==4.25.0
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.8.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.16.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.4.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.15
    - kiwisolver==1.4.8
    - lightning-utilities==0.11.9
    - llvmlite==0.43.0
    - lxml==5.2.1
    - markdown-it-py==2.2.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.6
    - mdurl==0.1.0
    - mistune==3.1.2
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.4.4
    - multiprocess==0.70.15
    - murmurhash==1.0.12
    - narwhals==1.42.1
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - nltk==3.8.1
    - notebook==7.4.4
    - notebook-shim==0.2.4
    - numba==0.60.0
    - numexpr==2.11.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - omegaconf==2.3.0
    - overrides==7.4.0
    - packaging==25.0
    - pandas==2.1.1
    - parso==0.8.4
    - pathos==0.3.0
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.3.7
    - plotly==5.24.1
    - polars==1.30.0
    - pox==0.3.3
    - ppft==1.7.6.7
    - preshed==3.0.9
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.43
    - propcache==0.3.1
    - protobuf==5.29.3
    - psutil==5.9.0
    - pyarrow==19.0.0
    - pyarrow-hotfix==0.6
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pyg-lib==0.4.0+pt26cu124
    - pygments==2.19.1
    - pygod==1.1.0
    - pynndescent==0.5.13
    - pyparsing==3.2.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.2.1
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==26.2.0
    - qtpy==2.4.1
    - referencing==0.30.2
    - regex==2024.11.6
    - requests==2.32.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.3.5
    - rpds-py==0.22.3
    - safetensors==0.4.3
    - scikit-learn==1.7.1
    - scikit-learn-intelex==20230426.111436
    - scipy==1.15.3
    - seaborn==0.13.2
    - send2trash==1.8.2
    - sentence-transformers==2.7.0
    - setuptools==78.1.1
    - shellingham==1.5.0
    - six==1.17.0
    - smart-open==5.2.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - spacy==3.7.2
    - spacy-curated-transformers==0.2.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.5.1
    - sympy==1.13.3
    - tenacity==9.0.0
    - terminado==0.17.1
    - thinc==8.2.2
    - threadpoolctl==3.5.0
    - tinycss2==1.4.0
    - tokenizers==0.21.1
    - tomli==2.2.1
    - topmost==0.0.5
    - torch==2.6.0
    - torch-geometric==2.5.2
    - torchaudio==2.6.0
    - torchdata==0.7.1
    - torchmetrics==1.4.0.post0
    - torchvision==0.21.0
    - tornado==6.5.1
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.52.4
    - triton==3.2.0
    - typer==0.9.0
    - typing-extensions==4.13.0
    - typing-inspection==0.4.0
    - umap-learn==0.5.7
    - unicodedata2==15.1.0
    - urllib3==2.5.0
    - wasabi==0.9.1
    - wcwidth==0.2.13
    - weasel==0.3.4
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - wheel==0.45.1
    - widgetsnbextension==4.0.13
    - xxhash==3.5.0
    - yarl==1.20.0
prefix: ~/miniconda3/envs/torch2
