_target_: modules.v17_CL_SimCSE_prev_next_pos_MLP_model.LitModule
model_cfg:
  encoder_pretrained_model_name: ${datamodule.pretrained_model_name}
  encoder_trainable: true
  cache_dir: ./data/model_cache
  mlp_hidden_dims: [768, 768, 768]
  cross_cl_alpha: 0.1
  cross_cl_gamma: 0.1
  hidden_dim: 768
optimizer_partial:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
encoder_lr: 1e-5
mlp_lr: 1e-4
linear_lr: 1e-3